#!/bin/bash

#
# Este programa prepara los archivos descargados del
# histórico de datos de madrid para que sean fácilmente
# insertables en una base de datos MongoDB.
#

C_RED="\x1B[0;31m"
C_GREEN="\x1B[0;32m"
C_YELLOW="\x1B[0;33m"
C_BLUE="\x1B[0;34m"
C_MAGENTA="\x1B[0;35m"
C_CYAN="\x1B[0;36m"
C_GRAY="\x1B[0;37m"
C_L_RED="\x1B[1;31m"
C_L_GREEN="\x1B[1;32m"
C_L_YELLOW="\x1B[1;33m"
C_L_BLUE="\x1B[1;34m"
C_L_MAGENTA="\x1B[1;35m"
C_L_CYAN="\x1B[1;36m"
C_L_WHITE="\x1B[1;37m"
C_TITLE="\x1B[48;5;26;1;37m"
C_TITLE_POS="\x1B[3;4H"
C_ERASE="\x1B[2J\x1B[0;0H"
C_ERASE_LINE="\x1B[2K"
C_ANSWER="\x1B[8;4H\x1B[J"
C_DOWNLOAD="\x1B[10;4H\x1B[J"
C_RESET="\x1B[0m"

#
# Muestra el título
#
function title {
  echo -e "${C_ERASE}${C_TITLE}${C_ERASE_LINE}\n${C_ERASE_LINE}\n${C_ERASE_LINE}${C_TITLE_POS}Madrid - Programa de preparación de datos\n${C_ERASE_LINE}\n${C_ERASE_LINE}\n${C_RESET}"
}

#
# Muestra el epílogo.
#
function epilogue {
  echo -e "\nHecho con ${C_L_RED}❤${C_RESET} por ${C_L_RED}ROJO 2${C_RESET} (http://rojo2.com)\n"
}

function decompress_file {

  INPUT_FILENAME="downloads/${1}_${2}.zip"
  echo -e "${C_ANSWER}Descomprimiendo archivo ${C_CYAN}${INPUT_FILENAME}${C_RESET}"
  OUTPUT=$(unzip -o ${INPUT_FILENAME} -d "data/")
  while read -r LINE; do

    # Obtiene el archivo descomprimido.
    DECOMPRESSED_FILE=$(grep -oE "[0-9_-]+.csv$" <<< $LINE)

    (cd mongocorto && node index.js "../data/$DECOMPRESSED_FILE" 172.17.0.2)

  done <<< $OUTPUT

}

#
# Descomprime los archivos zip en la carpeta data
#

title

if [[ -z $1 || -z $2 ]]; then
  echo -e "Uso: `basename($0)` <año> <mes>"
  exit 1
fi

decompress_file $1 $2
