#!/bin/bash

#
# Este programa descarga todos los archivos.
# @see http://datos.madrid.es/portal/site/egob/menuitem.c05c1f754a33a9fbe4b2e4b284f1a5a0/?vgnextoid=33cb30c367e78410VgnVCM1000000b205a0aRCRD&vgnextchannel=374512b9ace9f310VgnVCM100000171f5a0aRCRD&vgnextfmt=default
#

C_RED="\x1B[0;31m"
C_GREEN="\x1B[0;32m"
C_YELLOW="\x1B[0;33m"
C_BLUE="\x1B[0;34m"
C_MAGENTA="\x1B[0;35m"
C_CYAN="\x1B[0;36m"
C_GRAY="\x1B[0;37m"
C_L_RED="\x1B[1;31m"
C_L_GREEN="\x1B[1;32m"
C_L_YELLOW="\x1B[1;33m"
C_L_BLUE="\x1B[1;34m"
C_L_MAGENTA="\x1B[1;35m"
C_L_CYAN="\x1B[1;36m"
C_L_WHITE="\x1B[1;37m"
C_TITLE="\x1B[48;5;26;1;37m"
C_TITLE_POS="\x1B[3;4H"
C_ERASE="\x1B[2J\x1B[0;0H"
C_ERASE_LINE="\x1B[2K"
C_ANSWER="\x1B[8;4H\x1B[J"
C_RESET="\x1B[0m"

#
# Muestra el título
#
function title {
  echo -e "${C_ERASE}${C_TITLE}${C_ERASE_LINE}\n${C_ERASE_LINE}\n${C_ERASE_LINE}${C_TITLE_POS}Madrid - Programa de descarga del histórico de datos de tráfico\n${C_ERASE_LINE}\n${C_ERASE_LINE}\n${C_RESET}"
}

#
# Muestra el epílogo.
#
function epilogue {
  echo -e "\nHecho con ${C_L_RED}❤${C_RESET} por ${C_L_RED}ROJO 2${C_RESET} (http://rojo2.com)\n"
}

#
# Descarga los archivos via wget
#
# $1: URL
# $2: Mes
# $3: Año
#
function download_via_wget {
  OUTPUT_FILENAME="downloads/${3}_${2}.zip"
  wget --progress=bar --show-progress -q -O $OUTPUT_FILENAME $1
}

#
# Descarga un archivo usando WGET.
#
# $1: URL
# $2: Mes
# $3: Año
#
function download_file {
  if [[ ! -d downloads ]]; then
    mkdir -p downloads
  fi

  case $CHOOSE_MONTH in
    S|s)
      DOWNLOAD=1
      while [[ $DOWNLOAD =~ [^SsNn] ]]; do
        echo -e "${C_ANSWER}¿Quieres descargar ${C_CYAN}$2${C_RESET} de ${C_CYAN}$3${C_RESET}? (S/n)"
        read -s -n 1 DOWNLOAD
        case $DOWNLOAD in
          S|s)
            download_via_wget $1 $2 $3
          ;;
          *)
          ;;
        esac
      done
    ;;
    *)
      download_via_wget $1 $2 $3
    ;;
  esac
}

#
# Descarga todos los archivos de 2013.
#
function download_thirteen {
  # 2013 Julio
  download_file http://datos.madrid.es/egob/catalogo/208627-0-transporte-ptomedida-historico.zip "Julio" "2013"
  # 2013 Agosto
  download_file http://datos.madrid.es/egob/catalogo/208627-1-transporte-ptomedida-historico.zip "Agosto" "2013"
  # 2013 Septiembre
  download_file http://datos.madrid.es/egob/catalogo/208627-2-transporte-ptomedida-historico.zip "Septiembre" "2013"
  # 2013 Octubre
  download_file http://datos.madrid.es/egob/catalogo/208627-3-transporte-ptomedida-historico.zip "Octubre" "2013"
  # 2013 Noviembre
  download_file http://datos.madrid.es/egob/catalogo/208627-4-transporte-ptomedida-historico.zip "Noviembre" "2013"
  # 2013 Diciembre
  download_file http://datos.madrid.es/egob/catalogo/208627-5-transporte-ptomedida-historico.zip "Diciembre" "2013"
}

#
# Descarga todos los archivos de 2014.
#
function download_fourteen {
  # 2014 Enero
  download_file http://datos.madrid.es/egob/catalogo/208627-6-transporte-ptomedida-historico.zip "Enero" "2014"
  # 2014 Febrero
  download_file http://datos.madrid.es/egob/catalogo/208627-7-transporte-ptomedida-historico.zip "Febrero" "2014"
  # 2014 Marzo
  download_file http://datos.madrid.es/egob/catalogo/208627-8-transporte-ptomedida-historico.zip "Marzo" "2014"
  # 2014 Abril
  download_file http://datos.madrid.es/egob/catalogo/208627-9-transporte-ptomedida-historico.zip "Abril" "2014"
  # 2014 Mayo
  download_file http://datos.madrid.es/egob/catalogo/208627-10-transporte-ptomedida-historico.zip "Mayo" "2014"
  # 2014 Junio
  download_file http://datos.madrid.es/egob/catalogo/208627-11-transporte-ptomedida-historico.zip "Junio" "2014"
  # 2014 Julio
  download_file http://datos.madrid.es/egob/catalogo/208627-12-transporte-ptomedida-historico.zip "Julio" "2014"
  # 2014 Agosto
  download_file http://datos.madrid.es/egob/catalogo/208627-13-transporte-ptomedida-historico.zip "Agosto" "2014"
  # 2014 Septiembre
  download_file http://datos.madrid.es/egob/catalogo/208627-14-transporte-ptomedida-historico.zip "Septiembre" "2014"
  # 2014 Octubre
  download_file http://datos.madrid.es/egob/catalogo/208627-15-transporte-ptomedida-historico.zip "Octubre" "2014"
  # 2014 Noviembre
  download_file http://datos.madrid.es/egob/catalogo/208627-16-transporte-ptomedida-historico.zip "Noviembre" "2014"
  # 2014 Diciembre
  download_file http://datos.madrid.es/egob/catalogo/208627-17-transporte-ptomedida-historico.zip "Diciembre" "2014"
}

#
# Descarga todos los archivos de 2015.
#
function download_fifteen {
  # 2015 Enero
  download_file http://datos.madrid.es/egob/catalogo/208627-17-transporte-ptomedida-historico.zip "Enero" "2015"
  # 2015 Febrero
  download_file http://datos.madrid.es/egob/catalogo/208627-21-transporte-ptomedida-historico.zip "Febrero" "2015"
  # 2015 Marzo
  download_file http://datos.madrid.es/egob/catalogo/208627-22-transporte-ptomedida-historico.zip "Marzo" "2015"
  # 2015 Abril
  download_file http://datos.madrid.es/egob/catalogo/208627-23-transporte-ptomedida-historico.zip "Abril" "2015"
  # 2015 Mayo
  download_file http://datos.madrid.es/egob/catalogo/208627-24-transporte-ptomedida-historico.zip "Mayo" "2015"
  # 2015 Junio
  download_file http://datos.madrid.es/egob/catalogo/208627-25-transporte-ptomedida-historico.zip "Junio" "2015"
  # 2015 Julio
  download_file http://datos.madrid.es/egob/catalogo/208627-26-transporte-ptomedida-historico.zip "Julio" "2015"
  # 2015 Agosto
  download_file http://datos.madrid.es/egob/catalogo/208627-27-transporte-ptomedida-historico.zip "Agosto" "2015"
  # 2015 Septiembre
  download_file http://datos.madrid.es/egob/catalogo/208627-28-transporte-ptomedida-historico.zip "Septiembre" "2015"
  # 2015 Octubre
  download_file http://datos.madrid.es/egob/catalogo/208627-29-transporte-ptomedida-historico.zip "Octubre" "2015"
  # 2015 Noviembre
  download_file http://datos.madrid.es/egob/catalogo/208627-30-transporte-ptomedida-historico.zip "Noviembre" "2015"
  # 2015 Diciembre
  download_file http://datos.madrid.es/egob/catalogo/208627-31-transporte-ptomedida-historico.zip "Diciembre" "2015"
}

#
# Descarga todos los archivos de 2016.
#
function download_sixteen {
  # 2016 Enero
  download_file http://datos.madrid.es/egob/catalogo/208627-32-transporte-ptomedida-historico.zip "Enero" "2016"
  # 2016 Febrero
  download_file http://datos.madrid.es/egob/catalogo/208627-33-transporte-ptomedida-historico.zip "Febrero" "2016"
  # 2016 Marzo
  download_file http://datos.madrid.es/egob/catalogo/208627-34-transporte-ptomedida-historico.zip "Marzo" "2016"
  # 2016 Abril
  download_file http://datos.madrid.es/egob/catalogo/208627-35-transporte-ptomedida-historico.zip "Abril" "2016"
  # 2016 Mayo
  download_file http://datos.madrid.es/egob/catalogo/208627-36-transporte-ptomedida-historico.zip "Mayo" "2016"
  # 2016 Junio
  download_file http://datos.madrid.es/egob/catalogo/208627-37-transporte-ptomedida-historico.zip "Junio" "2016"
  # 2016 Julio
  download_file http://datos.madrid.es/egob/catalogo/208627-38-transporte-ptomedida-historico.zip "Julio" "2016"
  # 2016 Agosto
  download_file http://datos.madrid.es/egob/catalogo/208627-39-transporte-ptomedida-historico.zip "Agosto" "2016"
  # 2016 Septiembre
  download_file http://datos.madrid.es/egob/catalogo/208627-40-transporte-ptomedida-historico.zip "Septiembre" "2016"
  # 2016 Octubre
  download_file http://datos.madrid.es/egob/catalogo/208627-41-transporte-ptomedida-historico.zip "Octubre" "2016"
  # 2016 Noviembre
  download_file http://datos.madrid.es/egob/catalogo/208627-42-transporte-ptomedida-historico.zip "Noviembre" "2016"
  # 2016 Diciembre
  download_file http://datos.madrid.es/egob/catalogo/208627-43-transporte-ptomedida-historico.zip "Diciembre" "2016"
}

#
# Descarga el archivo completo de 2013.
#
function download_whole_thirteen {
  # 2013
  download_file http://datos.madrid.es/egob/catalogo/208627-19-transporte-ptomedida-historico.zip
}

#
# Descarga el archivo completo de 2014.
#
function download_whole_fourteen {
  # 2014
  download_file http://datos.madrid.es/egob/catalogo/208627-20-transporte-ptomedida-historico.zip
}

#
# Descarga el archivo de un año concreto.
#
# $1: Año que se va a descargar
#
function download_year {
  echo -e "${C_ANSWER}Descargando ${C_CYAN}$1${C_RESET}"
  case $1 in
    2013) download_thirteen ;;
    2014) download_fourteen ;;
    2015) download_fifteen ;;
    2016) download_fifteen ;;
  esac
}

#
# Descarga una lista.
#
# $1: Año que se va a descargar
#
function download {
  if [[ $CHOOSE_YEARS =~ [Ss] ]]; then
    DOWNLOAD=1
    while [[ $DOWNLOAD =~ [^SsNn] ]]; do
      echo -e "${C_ANSWER}¿Quieres descargar ${C_CYAN}$1${C_RESET}? (S/n)"
      read -s -n 1 DOWNLOAD
      case $DOWNLOAD in
        S|s)
          download_year $1
        ;;
      esac
    done
  else
    download_year $1
  fi
}

#
# Pregunta si los meses deben preguntarse de forma individual.
#
function months {
  CHOOSE_MONTH=1
  while [[ $CHOOSE_MONTH =~ [^SsNn] ]]; do
    echo -e "${C_ANSWER}¿Quieres seleccionar cada ${C_CYAN}mes${C_RESET} de forma individual? (S/n)"
    read -s -n 1 CHOOSE_MONTH
  done
}

#
# Pregunta si quieres descargar los años por separado.
#
function years {
  CHOOSE_YEARS=1
  while [[ $CHOOSE_YEARS =~ [^SsNn] ]]; do
    echo -e "${C_ANSWER}¿Quieres seleccionar cada ${C_CYAN}año${C_RESET} de forma individual? (S/n)"
    read -s -n 1 CHOOSE_YEARS
  done
}

title
years
months
download "2013"
download "2014"
download "2015"
download "2016"
