#!/usr/bin/env node
/**
 * Este archivo convierte pmed.csv en un JSON
 * más legible y con más sentido.
 */
const fs = require("fs");
const cp = require("child_process");
const iconv = require("iconv-lite");

function insert(str, pos, chr) {
  return str.slice(0, pos) + chr + str.slice(pos);
}

function getZone(zone) {
  switch(zone) {
    case "PUNTOS DE MEDIDA M-30": return "m30";
    case "PUNTOS DE MEDIDA URBANOS": return "city";
    default: return zone;
  }
}

console.log(
  JSON.stringify(
    iconv.decode(fs.readFileSync("pmed.csv"), "iso-8859-1")
      .split("\r\n")
      .map((line) => line.split(";"))
      .filter((line,index) => line.length > 1 && index > 0)
      .map((row) => {
        const [idelem,tipo_elem,identif,nombre,st_x,st_y] = row;
        const x = parseFloat(insert(st_x.replace(/\./g,""), 6, "."));
        const y = parseFloat(insert(st_y.replace(/\./g,""), 7, "."));
        const command = `cs2cs -f '%.16f' +nadgrids=@PENR2009.gsb +init=epsg:23030 +to +init=epsg:4326 << EOF\n${x} ${y}\n`;
        const output = cp.execSync(command, { encoding: "utf-8" });
        const [fullMatch, lng, lat] = output.match(/(-?[0-9]+(?:\.[0-9]+)?)\s(-?[0-9]+(?:\.[0-9]+)?)\s(-?[0-9]+(?:\.[0-9]+)?)/);
        return {
          location: {
            type: "Point",
            coordinates: [
              parseFloat(lat),
              parseFloat(lng)
            ],
          },
          id: parseInt(idelem),
          zone: getZone(tipo_elem),
          device: identif,
          description: nombre
        };
      }),
    null,
    "  "
  )
);
